/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardTelemedicineRouteImport } from './routes/dashboard.telemedicine'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard.reports'
import { Route as DashboardPharmacyRouteImport } from './routes/dashboard.pharmacy'
import { Route as DashboardPatientsRouteImport } from './routes/dashboard.patients'
import { Route as DashboardLabRouteImport } from './routes/dashboard.lab'
import { Route as DashboardIcuRouteImport } from './routes/dashboard.icu'
import { Route as DashboardEmergencyRouteImport } from './routes/dashboard.emergency'
import { Route as DashboardEhrRouteImport } from './routes/dashboard.ehr'
import { Route as DashboardChatRouteImport } from './routes/dashboard.chat'
import { Route as DashboardAppointmentsRouteImport } from './routes/dashboard.appointments'
import { Route as DashboardAiRouteImport } from './routes/dashboard.ai'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTelemedicineRoute = DashboardTelemedicineRouteImport.update({
  id: '/telemedicine',
  path: '/telemedicine',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPharmacyRoute = DashboardPharmacyRouteImport.update({
  id: '/pharmacy',
  path: '/pharmacy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPatientsRoute = DashboardPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLabRoute = DashboardLabRouteImport.update({
  id: '/lab',
  path: '/lab',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIcuRoute = DashboardIcuRouteImport.update({
  id: '/icu',
  path: '/icu',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEmergencyRoute = DashboardEmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEhrRoute = DashboardEhrRouteImport.update({
  id: '/ehr',
  path: '/ehr',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAiRoute = DashboardAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/ehr': typeof DashboardEhrRoute
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/icu': typeof DashboardIcuRoute
  '/dashboard/lab': typeof DashboardLabRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/pharmacy': typeof DashboardPharmacyRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/telemedicine': typeof DashboardTelemedicineRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/ehr': typeof DashboardEhrRoute
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/icu': typeof DashboardIcuRoute
  '/dashboard/lab': typeof DashboardLabRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/pharmacy': typeof DashboardPharmacyRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/telemedicine': typeof DashboardTelemedicineRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/ai': typeof DashboardAiRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/ehr': typeof DashboardEhrRoute
  '/dashboard/emergency': typeof DashboardEmergencyRoute
  '/dashboard/icu': typeof DashboardIcuRoute
  '/dashboard/lab': typeof DashboardLabRoute
  '/dashboard/patients': typeof DashboardPatientsRoute
  '/dashboard/pharmacy': typeof DashboardPharmacyRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/telemedicine': typeof DashboardTelemedicineRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/ai'
    | '/dashboard/appointments'
    | '/dashboard/chat'
    | '/dashboard/ehr'
    | '/dashboard/emergency'
    | '/dashboard/icu'
    | '/dashboard/lab'
    | '/dashboard/patients'
    | '/dashboard/pharmacy'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/telemedicine'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/dashboard/ai'
    | '/dashboard/appointments'
    | '/dashboard/chat'
    | '/dashboard/ehr'
    | '/dashboard/emergency'
    | '/dashboard/icu'
    | '/dashboard/lab'
    | '/dashboard/patients'
    | '/dashboard/pharmacy'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/telemedicine'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/dashboard/ai'
    | '/dashboard/appointments'
    | '/dashboard/chat'
    | '/dashboard/ehr'
    | '/dashboard/emergency'
    | '/dashboard/icu'
    | '/dashboard/lab'
    | '/dashboard/patients'
    | '/dashboard/pharmacy'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/telemedicine'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/telemedicine': {
      id: '/dashboard/telemedicine'
      path: '/telemedicine'
      fullPath: '/dashboard/telemedicine'
      preLoaderRoute: typeof DashboardTelemedicineRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/pharmacy': {
      id: '/dashboard/pharmacy'
      path: '/pharmacy'
      fullPath: '/dashboard/pharmacy'
      preLoaderRoute: typeof DashboardPharmacyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/patients': {
      id: '/dashboard/patients'
      path: '/patients'
      fullPath: '/dashboard/patients'
      preLoaderRoute: typeof DashboardPatientsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/lab': {
      id: '/dashboard/lab'
      path: '/lab'
      fullPath: '/dashboard/lab'
      preLoaderRoute: typeof DashboardLabRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/icu': {
      id: '/dashboard/icu'
      path: '/icu'
      fullPath: '/dashboard/icu'
      preLoaderRoute: typeof DashboardIcuRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/emergency': {
      id: '/dashboard/emergency'
      path: '/emergency'
      fullPath: '/dashboard/emergency'
      preLoaderRoute: typeof DashboardEmergencyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ehr': {
      id: '/dashboard/ehr'
      path: '/ehr'
      fullPath: '/dashboard/ehr'
      preLoaderRoute: typeof DashboardEhrRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/appointments': {
      id: '/dashboard/appointments'
      path: '/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardAppointmentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ai': {
      id: '/dashboard/ai'
      path: '/ai'
      fullPath: '/dashboard/ai'
      preLoaderRoute: typeof DashboardAiRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAiRoute: typeof DashboardAiRoute
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRoute
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardEhrRoute: typeof DashboardEhrRoute
  DashboardEmergencyRoute: typeof DashboardEmergencyRoute
  DashboardIcuRoute: typeof DashboardIcuRoute
  DashboardLabRoute: typeof DashboardLabRoute
  DashboardPatientsRoute: typeof DashboardPatientsRoute
  DashboardPharmacyRoute: typeof DashboardPharmacyRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTelemedicineRoute: typeof DashboardTelemedicineRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAiRoute: DashboardAiRoute,
  DashboardAppointmentsRoute: DashboardAppointmentsRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardEhrRoute: DashboardEhrRoute,
  DashboardEmergencyRoute: DashboardEmergencyRoute,
  DashboardIcuRoute: DashboardIcuRoute,
  DashboardLabRoute: DashboardLabRoute,
  DashboardPatientsRoute: DashboardPatientsRoute,
  DashboardPharmacyRoute: DashboardPharmacyRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTelemedicineRoute: DashboardTelemedicineRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
