declare module 'lucide-react' {
  import { FC, SVGProps, ForwardRefExoticComponent, RefAttributes } from 'react'
  type Icon = ForwardRefExoticComponent<SVGProps<SVGSVGElement> & RefAttributes<SVGSVGElement>>
  export const Icon: Icon
  export const createLucideIcon: (name: string, icon: any) => Icon
  
  export const Loader2: Icon
  export const Stethoscope: Icon
  export const ShieldCheck: Icon
  export const Activity: Icon
  export const Ambulance: Icon
  export const Menu: Icon
  export const X: Icon
  export const Bell: Icon
  export const BellRing: Icon
  export const ChevronDown: Icon
  export const ChevronDownIcon: Icon
  export const ChevronLeft: Icon
  export const ChevronRight: Icon
  export const ChevronRightIcon: Icon
  export const ChevronUp: Icon
  export const ChevronUpIcon: Icon
  export const Calendar: Icon
  export const CalendarDays: Icon
  export const CalendarCheck: Icon
  export const CalendarX: Icon
  export const Clock: Icon
  export const DollarSign: Icon
  export const Users: Icon
  export const Video: Icon
  export const VideoOff: Icon
  export const Phone: Icon
  export const PhoneCall: Icon
  export const PhoneOff: Icon
  export const MessageSquare: Icon
  export const MessageCircle: Icon
  export const Search: Icon
  export const Filter: Icon
  export const MoreHorizontal: Icon
  export const MoreVertical: Icon
  export const Plus: Icon
  export const Edit: Icon
  export const Edit3: Icon
  export const Trash2: Icon
  export const Check: Icon
  export const CheckCircle: Icon
  export const CheckCircle2: Icon
  export const CheckIcon: Icon
  export const CheckSquare: Icon
  export const AlertCircle: Icon
  export const AlertTriangle: Icon
  export const Info: Icon
  export const LogOut: Icon
  export const Settings: Icon
  export const Home: Icon
  export const FileText: Icon
  export const TrendingUp: Icon
  export const TrendingDown: Icon
  export const Star: Icon
  export const Eye: Icon
  export const EyeOff: Icon
  export const Mail: Icon
  export const Lock: Icon
  export const User: Icon
  export const UserCheck: Icon
  export const Upload: Icon
  export const ClipboardList: Icon
  export const Pill: Icon
  export const Syringe: Icon
  export const Heart: Icon
  export const RefreshCw: Icon
  export const ExternalLink: Icon
  export const Share2: Icon
  export const Download: Icon
  export const Printer: Icon
  export const MapPin: Icon
  export const Award: Icon
  export const Sparkles: Icon
  export const Bot: Icon
  export const Ban: Icon
  export const ArrowLeft: Icon
  export const ArrowRight: Icon
  export const ArrowUp: Icon
  export const ArrowDown: Icon
  export const Copy: Icon
  export const Save: Icon
  export const Moon: Icon
  export const Sun: Icon
  export const Globe: Icon
  export const Shield: Icon
  export const ShieldOff: Icon
  export const Wallet: Icon
  export const Banknote: Icon
  export const IndianRupee: Icon
  export const XIcon: Icon
  export type LucideIcon = Icon
  export const DotIcon: Icon
  export const LayoutDashboard: Icon
  export const CalendarRange: Icon
}
